AXF_project/urls.py
import mainapp
from django.contrib import admin
from django.urls import path, include
from mainapp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home),
    path('app/', include('mainapp.urls')),
]

mainapp/urls.py
import mainapp
from django.contrib import admin
from django.urls import path, include
from mainapp import views

urlpatterns = [
    path('', views.home),
    path('market/<int:categoryid>/<int:childid>/<int:sortid>', views.market),
    path('cart', views.cart),
    path('mine', views.mine),
    path('regist', views.regist),
    path('upload', views.upload),
    path('logout', views.logout),
    path('login', views.login),
    path('cart', views.cart),
    path('select/<int:cart_id>', views.selectCart),
    path('subShopping/<int:cart_id>', views.subShopping),
    path('addShopping/<int:cart_id>', views.addShopping),
    path('order/<str:num>', views.order),
    path('pay/<str:num>/<int:payType>',views.pay)
]

mainapp/models.py
from django.db import models

# Create your models here.
class TopModel(models.Model):
    trackid = models.CharField(primary_key=True, max_length=50)
    img = models.CharField(max_length=300)
    name = models.CharField(max_length=50)
    class Meta:
        abstract=True
class TopWheel(TopModel):
    class Meta:
        db_table = 'axf_wheel'

class TopMenu(TopModel):
    position = models.IntegerField(default=1)
    class Meta:
        db_table = 'axf_nav'


class Mustbuy(TopModel):
    class Meta:
        db_table = 'axf_mustbuy'

class Shop(TopModel):
    position = models.IntegerField(default=1)
    class Meta:
        db_table = 'axf_shop'



# class MainShow(models.Model):
#     trackid = models.CharField(max_length=10)
#     name = models.CharField(max_length=20)
#     img = models.CharField(max_length=100)
#     categoryid = models.CharField(max_length=10)
#     brandname = models.CharField(max_length=20)
#
#     img1 = models.CharField(max_length=100)
#     childcid1 = models.CharField(max_length=10)
#     productid1 = models.CharField(max_length=10)
#     longname1 = models.CharField(max_length=50)
#     price1 = models.CharField(max_length=10)
#     marketprice1 = models.CharField(max_length=10)
#
#     img2 = models.CharField(max_length=100)
#     childcid2 = models.CharField(max_length=10)
#     productid2 = models.CharField(max_length=10)
#     longname2 = models.CharField(max_length=50)
#     price2 = models.CharField(max_length=10)
#     marketprice2 = models.CharField(max_length=10)
#
#     img3 = models.CharField(max_length=100)
#     childcid3 = models.CharField(max_length=10)
#     productid3 = models.CharField(max_length=10)
#     longname3 = models.CharField(max_length=50)
#     price3 = models.CharField(max_length=10)
#     marketprice3 = models.CharField(max_length=10)
#
#
#     class Meta:
#         db_table = 'axf_mainshow'
# 热购的品牌
class MainShowParent(models.Model):
    trackid = models.CharField(max_length=10)
    name = models.CharField(max_length=20)
    img = models.CharField(max_length=100)

    categoryid = models.CharField(max_length=10)
    brandname = models.CharField(max_length=20)
    class Meta:
        db_table = 'axf_brand'
# 品牌下的商品
class BrandProduct(models.Model):
    img = models.CharField(max_length=100)
    childcid = models.CharField(max_length=10)
    productid = models.CharField(max_length=10)
    longname = models.CharField(max_length=50)
    price = models.CharField(max_length=10)
    marketprice = models.CharField(max_length=10)
    brand = models.ForeignKey(MainShowParent,on_delete=models.CASCADE)
    class Meta:
        db_table = 'axf_brand_product'

#食品分类
# axf_foodtypes(typeid,typename,childtypenames,typesort)
class FoodType(models.Model):
    typeid = models.CharField(primary_key=True,max_length=10)
    typename = models.CharField(max_length=50)
    childtypenames = models.CharField(max_length=200)
    typesort = models.IntegerField(default=1)
    class Meta:
        db_table = 'axf_foodtypes'


# axf_goods(productid,productimg,productname,productlongname,isxf,pmdesc,specifics,
# price,marketprice,categoryid,childcid,childcidname,dealerid,storenums,productnum)
class Goods(models.Model):
    productid = models.CharField(max_length=10,primary_key=True)
    productimg = models.CharField(max_length=300)
    productname = models.CharField(max_length=100)
    productlongname = models.CharField(max_length=100)
    isxf = models.BooleanField(default=1)
    pmdesc = models.IntegerField(default=1)
    specifics = models.CharField(max_length=100)
    price = models.DecimalField(default=0.0,max_digits=10,decimal_places=2)
    marketprice = models.DecimalField(default=0.0,max_digits=10,decimal_places=2)
    categoryid = models.IntegerField(default=0)
    childcid = models.IntegerField(default=0)
    childcidname = models.CharField(max_length=100)
    dealerid = models.CharField(max_length=10)
    storenums = models.IntegerField(default=1)
    productnum = models.IntegerField(default=0)
    class Meta:
        db_table = 'axf_goods'

class UserManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(state = True)


class User(models.Model):
    userName = models.CharField(max_length=50)
    userPasswd = models.CharField(max_length=32)
    phone = models.CharField(max_length=12)
    address = models.CharField(max_length=100, default='')
    city = models.CharField(max_length=50, default='')
    nickName = models.CharField(max_length=50, verbose_name='昵称')
    imgPath = models.CharField(max_length=100, default='')
    token = models.CharField(max_length=32, default='')
    state = models.BooleanField(default=True, verbose_name='用户状态')
    money = models.DecimalField(default=0,max_digits=20,decimal_places=2)

    objects = UserManager()

    def delete(self, using=None, keep_parents=False):
        self.state = False
        self.save()
        return '已注销'
    class Meta:
        db_table = 'axf_user'


class DeliveryAddress(models.Model):
    # 收件地址模型类
    name = models.CharField(max_length=20,
                            verbose_name='收件人')
    phone = models.CharField(max_length=12, verbose_name='收件人电话')
    address_detail = models.TextField(default='',
                                      verbose_name='收货地址')

    user = models.ForeignKey(User,
                             on_delete=models.CASCADE)

    class Meta:
        db_table = 'axf_address'

class Cart(models.Model):
    user = models.ForeignKey(User,
                             on_delete=models.CASCADE)

    goods = models.ForeignKey(Goods,
                             on_delete=models.CASCADE)

    # 数量
    cnt = models.IntegerField(default=1)

    # 是否被选择
    isSelected = models.BooleanField(default=True)

    class Meta:
        db_table = 'axf_cart'


# 订单
class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    # 订单的收货地址
    orderAdress = models.ForeignKey(DeliveryAddress,
                                    on_delete=models.SET_NULL,
                                    null=True)
    # 订单的单号
    orderNum = models.CharField(primary_key=True,
                                max_length=50, verbose_name='订单号')

    # 订单的总金额
    orderPrice = models.DecimalField(max_digits=10, decimal_places=2, default=0)

    # 订单的支付状态
    pay_states = ((0,'待支付'),(1,'已支付'),(2,'正在支付中'),(3,'已退款'))
    payState = models.IntegerField(choices=pay_states, default=0)

    # 支付的方式
    pay_types = ((0, '余款'), (1, '支付宝'), (2, '微信'))
    payType = models.IntegerField(choices=pay_types, default=0)

    @property
    def payStateName(self):
        return self.pay_states[self.payState][1]

    # 订单的派送状态
    order_states = ((0,'待派送'), (1,'已派送'),(2,'已到达'),(3,'已签收'),(4,'拒收'),(5,'未到达'),)
    orderState = models.IntegerField(choices=order_states, default=0)

    @property
    def orderStateName(self):
        return self.order_states[self.orderState][1]

    # 生成订单时间
    orderTime = models.DateTimeField(auto_now_add=True)

    # 订单最近变更时间
    orderLastTime = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'axf_order'

# 订单明细
class OrderGoods(models.Model):  # 订单明细
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    goods = models.ForeignKey(Goods, on_delete=models.SET_NULL, null=True)
    cnt = models.IntegerField(default=1)
    price = models.DecimalField(default=0, max_digits=10, decimal_places=2, verbose_name='小计')

    class Meta:
        db_table = 'axf_order_goods'

templates/base.html
<!DOCTYPE html>
<html style="font-size: 40px;" lang="zh-CN" >
{% load static from staticfiles %}
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>
    <link rel="stylesheet" href="{% static 'main/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'main/css/swiper.min.css' %}">
    <link rel="stylesheet" href="{% static 'main/css/reset.css' %}">
    <link rel="stylesheet" href="{% static 'main/css/base.css' %}">
    {% block extCss %}
{#        扩展的CSS样式文件 #}
    {% endblock %}
</head>
<body>
<header></header>
{% block content %}
{% endblock %}
<footer>
    <a class="home" href="/">
        <dl>
            <dt><span></span></dt>
            <dd>主页</dd>
        </dl>
    </a>
    <a class="market" href="/app/market/0/0/0">
        <dl>
            <dt><span></span></dt>
            <dd>闪购</dd>
        </dl>
    </a>

    <a class="cart" href="/app/cart">
        <dl>
            <dt><span></span></dt>
            <dd>购物车</dd>
        </dl>
        <p id="cartCnt">0</p>
    </a>

    <a class="mine" href="/app/mine">
        <dl>
            <dt><span></span></dt>
            <dd>我的</dd>
        </dl>
    </a>

</footer>
<script src="{% static 'main/js/jquery.min.js' %}"></script>
<script src="{% static 'main/js/bootstrap.min.js' %}"></script>
<script src="{% static 'main/js/swiper.min.js' %}"></script>
<script src="{% static 'main/js/base.js' %}"></script>
{% block extJs %}
{#    扩展的js#}
{% endblock %}
</body>
</html>

templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block extCss %}
    <link rel="stylesheet" href="{% static 'cart/css/cart.css' %}">
{% endblock %}

{% block content %}

    <div id="cart">
        <h3>我的购物车</h3>
        <section class="full">

            <section>
                {#  收货信息 #}
                <ul>
                    <li style="border-bottom: 1px solid gray;">
                        <span style="font-size: 0.35rem;color: dodgerblue">收件地址信息</span><a href="#"
                                                                                           class="btn btn-link change">修改</a>
                    </li>
                    <li>
                        <div class="clear">
                            <p class="infoJustify"><strong>收件人: </strong></p>
                            <p><span>{{ myAddress.name }}</span></p>
                        </div>
                        <div class="clear">
                            <p class="infoJustify"><strong>手机号: </strong></p>
                            <p><span>{{ myAddress.phone }}</span></p>
                        </div>
                        <div class="clear">
                            <p class="infoJustify"><strong>收件地址: </strong></p>
                            <p><span>{{ myAddress.address_detail }}</span></p>
                        </div>
                    </li>
                </ul>

                <section class="bill">
                    <p>闪送超市</p>
                    <p>¥0起送,22:00前满¥30免运费</p>
                    <a>凑单专区</a>
                </section>


                <section class="delivery">
                    <span>收货时间</span>
                    <span>一小时送达</span>
                    <a>可预订&gt;</a>
                </section>

                <section class="delivery">
                    <span>收货备注</span>
                    <input type="text"
                           name="noteText"
                           placeholder="可输入20字以内特殊要求内容"/>
                </section>

                {#   购物车中物品  #}
                <menu>
                    <ul>
                        {% for cart in carts %}
                            <li class="menuList">
                                <div class="confirm">
                                <span class="isChose">
                                    <span id="{{ cart.id }}">
                                        {% if  cart.isSelected %}
                                        √
                                        {% endif %}
                                    </span>
                                </span>
                                </div>
                                <a href="#">
                                    <img src="{{ cart.goods.productimg }}"/>
                                    <p>{{ cart.goods.productname }}</p>
                                    <span>￥{{ cart.goods.price }}</span>
                                </a>
                                <section>
                                    <button title="{{ cart.id }}" class="subShopping">-</button>
                                    <span>{{ cart.cnt }}</span>
                                    <button title="{{ cart.id }}" class="addShopping">+</button>
                                </section>

                            </li>
                        {% endfor %}
                        <li class="payTheBill">
                            <div class="confirm">
                            <span id="allChose"><span>
                            </span></span>
                            </div>
                            <p><span>全选</span><span>共计:</span><span id="totalPrice">{{ totalPrice }}</span></p>

                        </li>
                        <li style="background-color:white;text-align: right;">
                            <a id="toOrder" class="btn btn-info" style="margin: 0.5rem;">立即下单</a>
                        </li>
                    </ul>

                </menu>
            </section>

        </section>

    </div>

{% endblock %}

{% block extJs %}
    <script src="{% static 'cart/js/cart.js' %}"></script>
{% endblock %}

templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block extCss %}
    <link rel="stylesheet" href="{% static 'home/css/home.css' %}">
{% endblock %}
{% block content %}
    <div id="home">
        {#    头部的轮播#}
        <section class="swiper-container" id="topSwiper">
            <div class="swiper-wrapper">
                {% for topwWheel in topWheels %}
                    <div class="swiper-slide"><img src="{{ topwWheel.img }}"></div>
                {% endfor %}
            </div>
            <!-- 如果需要分页器 -->
            <div class="swiper-pagination"></div>
        </section>
        <section class="topMenu">
            <nav>
                <ul>
                    {% for topMenu in topMenus %}
                    <Li>
                        <a href="#">
                            <img src="{{ topMenu.img }}">
                            <span>{{ topMenu.name }}</span>
                        </a>
                    </Li>
                   {% endfor %}
                </ul>
            </nav>
            <menu class="swiper-container swiperMenu" id="swiperMenu">
                <ul class="swiper-wrapper">
                    {% for item in mustbuylist %}
                        <Li class="swiper-slide">
                            <a><img src="{{ item.img }}"/></a>
                        </Li>
                    {% endfor %}
                </ul>
            </menu>
        </section>
    <section class="CVS">
        <h2>
            <img src="{{shop1.img}}" alt="{{shop1.name}}"/>
        </h2>

        <fieldset>
            {% for x in shop2 %}
                <a href="#">
                    <img src="{{x.img}}" alt="{{x.name}}"/>
                </a>
            {% endfor %}
        </fieldset>

        <ul>
            {% for x in shop3 %}
                <li>
                    <a href="#">
                        <img src="{{x.img}}" />
                        <span>{{x.name}}</span>
                    </a>
                </li>
            {% endfor %}
        </ul>

        <ol>
            {% for x in shop4 %}
                <li><a href="#"><img src="{{x.img}}" alt="{{x.name}}"/></a></li>
            {% endfor %}
        </ol>
    </section>
    <section class="mainInfo">
        {% for brand in brandList%}
            <section>
                <h3>
                    {{brand.name}}
                    <a ui-sref="#">更多></a>
                    <span></span>
                </h3>
                <div>
                    <a href="#"><img src="{{brand.img}}" alt="brand.name"/></a>
                </div>
                <ul>
                    {% for item in brand.brandproduct_set.all %}
                    <li>
                        <a href="#">
                            <img src="{{item.img}}"/>
                            <span class="description">{{item.longname}}</span>
                            <span>¥{{item.price}}</span>
                            <s>¥{{item.marketprice}}</s>
                        </a>
                        <button><span>&#43;</span></button>
                    </li>
                    {% endfor %}
                </ul>
            </section>
        {% endfor %}
    </section>
    <div class="clearfix" style="height: 1.7rem"></div>
    </div>

{% endblock %}

{% block extJs %}
    <script src="{% static 'home/js/home.js' %}"></script>
{% endblock %}

templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block extCss %}
    <link rel="stylesheet" href="{% static 'mine/css/login.css' %}">
{% endblock %}

{% block content %}

    <div id="login">

        <h3>用户登录</h3>
        <form class="form-horizontal" method="post" action="/app/login">
        {% csrf_token %}
        <div class="input-group">
            <span class="input-group-addon">账号</span>
            <input class="form-control" title="账号" name="username" >
        </div>
        <p class="error">账号不能为空</p>
        <div class="input-group">
            <span class="input-group-addon">口令</span>
            <input class="form-control" title="口令" name="passwd" type="password">
        </div>
        <p class="error">口令不能为空</p>

        <div class="input-group" style="margin: 0px auto;">
            <button type="button" onclick="submitForm()" class="btn btn-success">登录</button>
            <a class="btn btn-link" href="/app/regist">未注册用户，请先注册</a>
        </div>

    </form>

    </div>

{% endblock %}

{% block extJs %}
    <script src="{% static 'mine/js/login.js' %}"></script>
{% endblock %}

templates/market.html
{% extends 'base.html' %}
{% load static %}
{% block extCss %}
    <link rel="stylesheet" href="{% static 'market/css/market.css' %}">
{% endblock %}

{% block content %}
    <div id="market">
        {#  左侧类型 #}
        <aside>
            <ul>
                {% for foodType in foodTypes %}
                    <li>

                        <a href="/app/market/{{ foodType.typeid }}/0/0">

                            {% ifequal categoryid foodType.typeid %}
                                <span class="yellowSlide"></span>
                            {% endifequal %}
                            {{ foodType.typename }}
                        </a>
                    </li>
                {% endfor %}
            </ul>
        </aside>
        {#    右边内容   #}
        <section>
            <nav>
                <ul>
                    <li>
                        <span id="allType">全部分类&nbsp;<span class="glyphicon glyphicon-chevron-up"></span></span>
                    </li>
                    <li>
                        <span id="goodsSort">综合排序&nbsp;<span class="glyphicon glyphicon-chevron-up"></span></span>
                    </li>
                </ul>
            </nav>

            <menu>
                {# ul->li 显示商品 #}
                <ul>
                    {% for goods in goodsList %}
                        <li>
                            <a href="#">
                                <img src="{{ goods.productimg }}">
                                <article class="shoppingInfo">
                                    <h6>${{ goods.productlongname }}</h6>
                                    <p class="detailTag"><span>精选</span><span>{{ goods.productnum }}</span></p>
                                    <span class="unit">{{ goods.specifics }}</span>
                                    <p class="price">
                                        <span>￥{{ goods.price }}</span><s><span>{{ goods.marketprice }}</span></s></p>
                                </article>
                                <div class="clearfix"></div>
                            </a>
                            <section>
                                <button title="{{ goods.productid }}" class="addShopping">+</button>
                            </section>
                        </li>
                    {% endfor %}
                </ul>

                <div id="typeSortDiv">
                    <div id="typeDiv">
                        {% for childType in childTypes %}
                            <a href="/app/market/{{ categoryid }}/{{ childType.id }}/0">
                                {% ifequal childType.id childid %}
                                    <span class="selected">
                                {% else %}
                                    <span>
                                {% endifequal %}
                                {{ childType.name }}</span></a>
                        {% endfor %}

                    </div>
                    <div id="sortDiv">
                        <a href="/app/market/{{ categoryid }}/{{ childid }}/1">
                            {% if sortid == 1 %}
                                <span class="selected">
                            {% else %}
                                <span>
                            {% endif %}
                            最高价格</span>
                        </a>
                        <a href="/app/market/{{ categoryid }}/{{ childid }}/2">
                            {% if sortid == 2 %}
                                <span class="selected">
                            {% else %}
                                <span>
                            {% endif %}
                            最低价格</span>
                        </a>
                        <a href="/app/market/{{ categoryid }}/{{ childid }}/3">
                            {% if sortid == 3 %}
                                <span class="selected">
                            {% else %}
                                <span>
                            {% endif %}
                            销量最高</span>
                        </a>
                    </div>
                </div>
            </menu>

        </section>
    </div>
{% endblock %}

{% block extJs %}
    <script src="{% static 'market/js/market.js' %}"></script>
{% endblock %}

templates/mine.html
{% extends 'base.html' %}
{% load static %}
{% block extCss %}
    <link rel="stylesheet" href="{% static 'mine/css/mine.css' %}">
{% endblock %}

{% block content %}
    <input type="file" onchange="upload(this.files[0])"
           id="file" style="display: none">
    <div id="mine">
        <section class="fixed">
            <span><img id="userImg" onclick="file.click()" src="{% static loginUser.imgPath %}"></span>
            <p><a href="#"> {{ loginUser.nickName }}</a></p>
            <p><span class="glyphicon glyphicon-fire"></span><span> VIP10 级</span></p>
            <a id="regis" href="/app/regist">注册</a>
            <p><span class="glyphicon glyphicon-heart"></span>我的收藏</p>
        </section>
        <section class="my">
            <p><span>我的订单</span><a href="#">查看全部&gt;</a></p>
            <nav id="nav">
            <ul>
                {% for nav in navs %}
            <li>
               <a href="{{ nav.url }}">
                   <dl>
                       <dt><span class="{{ nav.icon }}"></span></dt>
                       <dd>{{ nav.name }}</dd>
                   </dl>
               </a>
            </li>
            {% endfor %}
            </ul>
            </nav>
            <menu>
                <ul>
                    {% for menu in menus %}
                        <li>
                            <a href="{{ menu.url }}">
                                <dl>
                                    <dt><span class="{{ menu.icon }}"></span></dt>
                                    <dd>{{ menu.name }}</dd>
                                </dl>
                            </a>
                        </li>
                    {% endfor %}
                </ul>
            </menu>
            <p>
                <a href="/app/logout">退出登录</a>
            </p>
        </section>
    </div>
{% endblock %}

{% block extJs %}
    <script src="{% static 'mine/js/mine.js' %}"></script>
{% endblock %}

templates/order.html
{% extends 'base.html' %}
{% load static %}
{% block extCss %}
    <link rel="stylesheet" href="{% static 'order/css/order.css' %}">
{% endblock %}

{% block content %}
    <div id="order">
        <p>
            <button id="backBtn" class="btn btn-xs btn-info">返回</button>
        <div class="clearfix"></div>
        </p>
        <h3>我的订单</h3>

        <div>
            <section class="orderInfo">
                <p><strong>订单金额:</strong><span>￥{{ order.orderPrice }} 元</span></p>
                <p><strong>收货信息:</strong>
                    <span>{{ order.orderAdress.address_detail }}</span>
                    <span>{{ order.orderAdress.name }}</span>
                    <span>{{ order.orderAdress.phone }}</span>
                </p>
            </section>

            <menu id="orderGoods">
                <ul>
                    {% for orderitem in order.ordergoods_set.all %}

                        <li>
                            <dl>
                                <dt>
                                    <img src="{{ orderitem.goods.productimg }}">
                                </dt>
                                <dd><span>{{ orderitem.goods.productname|truncatechars:8 }}</span></dd>
                            </dl>
                        </li>
                    {% endfor %}
                </ul>
            </menu>

            <div id="payBtnDiv" title="{{ order.orderNum }}">
                <button title="0" class="btn btn-warning">余款</button>
                <button title="1" class="btn btn-info">支付宝</button>
                <button title="2" class="btn btn-success">微信</button>
            </div>
        </div>

    </div>

    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" >
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-body">
                     <span id="payMsg">正在支付...</span>
                </div>
            </div>
        </div>
    </div>


{% endblock %}

{% block extJs %}
    <script src="{% static 'order/js/order.js' %}"></script>
{% endblock %}

templates/regist.html
{% extends 'base.html' %}
{% load static %}
{% block extCss %}
    <link rel="stylesheet" href="{% static 'mine/css/register.css' %}">
{% endblock %}
{% block content %}
    <div id="register">
        <a class="btn btn-default" href="#"><span class="glyphicon glyphicon-chevron-left"/><span>返回</span> </a>
    <h3>用户注册</h3>
    <form class="form-horizontal" method="post" action="/app/regist">
        {% csrf_token %}
        <div class="input-group">
            <span class="input-group-addon">账号</span>
            <input class="form-control" title="账号" name="username" placeholder="不能少于10个字符" >
        </div>
        <p class="error">错误信息</p>
        <div class="input-group">
            <span class="input-group-addon">昵称</span>
            <input class="form-control" title="昵称" name="nickname" placeholder="不能少于10个字符" >
        </div>
        <p class="error">错误信息</p>
        <div class="input-group">
            <span class="input-group-addon">口令</span>
            <input class="form-control" title="口令" name="passwd" type="password" placeholder="可能不能少于8个字符">
        </div>
        <p class="error">错误信息</p>
        <div class="input-group">
            <span class="input-group-addon">验证</span>
            <input class="form-control" title="确认口令" name="passwd2" type="password"  placeholder="再一次输入口令">
        </div>
        <p class="error">错误信息</p>
        <div class="input-group">
            <span class="input-group-addon">手机</span>
            <input class="form-control" title="手机号" name="phone" placeholder="请输入您的手机号">
            <span class="input-group-addon" id="sendSmcode">发送验证码</span>
        </div>
        <p class="error">错误信息</p>
        <div class="input-group">
            <span class="input-group-addon">验证码</span>
            <input class="form-control" title="验证码" name="smscode" placeholder="输入您收的短信验证码" style="width: 5rem">
        </div>
        <p class="error">错误信息</p>
        <div class="input-group" style="margin: 0px auto;">
            <button type="button" onclick="submitForm()" class="btn btn-success">注册</button>
            <a class="btn btn-link" href="/app/login">已有用户登录</a>
        </div>
    </form>
</div>
{% endblock %}
{% block extJs %}
    <script src="{% static 'mine/js/regist.js' %}"></script>
{% endblock %}